import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AsideLeft from "@/components/aside-left";
import Header from "@/components/header";
import { returnData } from "../../public/assets/data/data-utils";
import { useLanguageStore } from "@/store/languageStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Help Pass",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased lg:ml-72`}>
        <Header />
        <AsideLeft />
        {children}
      </body>
    </html>
  );
}
