import "./globals.css";
import type { Metadata } from "next";
import AsideLeft from "@/components/aside-left";
import Header from "@/components/header";
import { Plus_Jakarta_Sans } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500"], // regular / medium
  variable: "--font-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Help Pass",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="pt-br">
      <body className={`${jakarta.variable} font-sans font-normal relative antialiased lg:ml-72 bg-neutral`}>
        <Header />
        <AsideLeft />
        {children}
      </body>
    </html>
  );
}
