import "../globals.css";
import type { Metadata } from "next";
import AsideLeft from "@/components/aside-left";
import Header from "@/components/header";
import { Plus_Jakarta_Sans } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import PASSLogo from "@/publicassets/images/logo/logo_pass_2025_chumbo.svg";
import clsx from "clsx";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500"], // regular / medium
  variable: "--font-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Help Center Pass",
  description: "Generated by create next app",
  icons: [
    {
      url: "/assets/images/logo/logo_pass_2025_white.svg",
      type: "image/svg+xml",
      sizes: "2x2" // ou qualquer tamanho desejado
    }
  ]
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={
        clsx(
          jakarta.variable,
          "font-sans font-normal",
          `min-h-screen relative antialiased  bg-neutral`,
          //"lg:ml-[18.72rem]",
          "flex flex-col"
        )
      }>
        <NextIntlClientProvider
          locale={locale}
          messages={messages}
        >
          <>
            <Header />
            <AsideLeft />
            {children}
          </>
        </NextIntlClientProvider>
      </body>

    </html>
  );
}
