import "../globals.css";
import type { Metadata } from "next";
import AsideLeft from "@/components/aside-left";
import Header from "@/components/header";
import { Plus_Jakarta_Sans } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500"], // regular / medium
  variable: "--font-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Help Pass",
  description: "Generated by create next app",
};

export default async function RootLayout({ 
  children,
  params
 }: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  const { locale } = await params;
  
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  
  const messages = await getMessages();
  
  return (
    <html lang={locale}>
      <body className={`${jakarta.variable} flex  flex-col min-h-screen font-sans font-normal relative antialiased lg:ml-72 bg-neutral`}>
        <NextIntlClientProvider
          locale={locale}
          messages={messages}
        >
          <>
            <Header />
            <AsideLeft />
            {children}
          </>
        </NextIntlClientProvider>
      </body>

    </html>
  );
}
